/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.muates.kafkamodel.avro;
@org.apache.avro.specific.AvroGenerated
public enum SocialInteractionType implements org.apache.avro.generic.GenericEnumSymbol<SocialInteractionType> {
  POST_LIKE, POST_COMMENT, COMMENT_LIKE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SocialInteractionType\",\"namespace\":\"com.muates.kafkamodel.avro\",\"symbols\":[\"POST_LIKE\",\"POST_COMMENT\",\"COMMENT_LIKE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
